test_dcache:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DCacheTest

test_amo:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DCacheAMOTest

test_mmio:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DCacheMMIOTest

test_forward:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DCacheForwardTest

test_bypass:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DCacheBypassTest

test_meta:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).MetaArrayTest

test_data:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DataArrayTest