test_dcache:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DCacheSpec

test_meta:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).MetaArrayTest

test_data:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DataArrayTest

test_wbu:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).WriteBackTest