test_all:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).*Test

test_dcache:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DCacheTest

test_amo:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DCacheAMOTest

test_bypass:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DCacheBypassTest

test_meta:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).MetaArrayTest

test_data:
	mill -i $(PRJ)[$(CHISEL_VERSION)].test.testOnly $(PRJ).DataArrayTest