find . -name "*.scala" |xargs -n1 sed -i 's/\.asUInt()/\.asUInt/g'
find . -name "*.scala" |xargs -n1 sed -i 's/\.asSInt()/\.asSInt/g'
find . -name "*.scala" |xargs -n1 sed -i 's/\.asBools()/\.asBools/g'
find . -name "*.scala" |xargs -n1 sed -i 's/\.fire()/\.fire/g'
find . -name "*.scala" |xargs -n1 sed -i 's/MultiIOModule/Module/g'
find . -name "*.scala" |xargs -n1 sed -i 's/import Chisel/import chisel3/g'
find . -name "*.scala" |xargs -n1 sed -i 's/import chipsalliance.rocketchip.config/import org.chipsalliance.cde.config/g'
find . -name "*.scala" |xargs -n1 sed -i 's/\.andR()/\.andR/g'
find . -name "*.scala" |xargs -n1 sed -i 's/\.orR()/\.orR/g'
find . -name "*.scala" |xargs -n1 sed -i 's/\.asBool()/\.asBool/g'
find . -name "*.scala" |xargs -n1 sed -i 's/\@chiselName//g'
find . -name "*.scala" |xargs -n1 sed -i 's/import freechips.rocketchip.config/import org.chipsalliance.cde.config/g'
find . -name "*.scala" |xargs -n1 sed -i 's/import chsiel3.experimental.chiselName//g'
find . -name "*.scala" |xargs -n1 sed -i 's/import chisel3.internal.naming.chiselName//g'

